# .travis.yml 文件

# 声明构建语言环境
language: android
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-29.0.2
    - android-29
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
script:
  # 生成 APK
  - ./gradlew assembleRelease

before_deploy:
  - ls app/build/outputs/apk/

# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  token:
    secure: ${GH_TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/app-release-unsigned.apk
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true