# .travis.yml

language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # Android Support Repository
    - extra-android-m2repository

    # Support Library
    - extra-android-support
script:
  # 生成 APK
  - ./gradlew assembleRelease

before_deploy:
  - ls app/build/outputs/apk/

# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  token:
    secure: ${GH_TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/release/app-release-unsigned.apk
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true